edit_video_path: results/woman-running_sculpture/result.mp4
original_video_path: data/woman-running_sculpture/ddim_latents/original.mp4
output_path: results/woman-running_sculpture

# foreground mask of the first frame to calculate trajectories only on the foreground
use_mask: False
mask_path: null

cotracker_model_path: /PHShome/ml1833/code/co-tracker/checkpoints/scaled_offline.pth