video_path: data/davis/blackswan
save_dir: data/davis/blackswan/ddim_latents
max_number_of_frames: 24

n_timesteps: 999
prompt: Amazing quality, masterpiece, A black swan swimming in the river.
negative_prompt: ""
save_ddim_reconstruction: data/davis/blackswan/ddim_rec # False