video_path: data/loveu/eiffel-flyover
save_dir: data/loveu/eiffel-flyover/ddim_latents
max_number_of_frames: 24

n_timesteps: 999
prompt: Amazing quality, masterpiece, Drone flyover of the Eiffel Tower in front of the city, sunset.
negative_prompt: ""
save_ddim_reconstruction: data/loveu/eiffel-flyover/ddim_rec # False