video_path: data/woman-running
save_dir: data/woman-running/ddim_latents
max_number_of_frames: 24

n_timesteps: 999
prompt: Amazing quality, masterpiece, A woman is running in a park
negative_prompt: ""
save_ddim_reconstruction: data/woman-running/ddim_rec #False