video_path: data/car-turn16
save_dir: data/car-turn16/ddim_latents
max_number_of_frames: 40

n_timesteps: 999
prompt: Amazing quality, masterpiece. A car is running on the road.
negative_prompt: ""
save_ddim_reconstruction: data/car-turn/ddim_rec #False