video_path: data/wolf
save_dir: data/wolf/ddim_latents
max_number_of_frames: 24

n_timesteps: 999
prompt: Amazing quality, masterpiece, A wolf is looking around.
negative_prompt: ""
save_ddim_reconstruction: data/wolf/ddim_rec #False