video_path: data/davis/camel
save_dir: data/davis/camel/ddim_latents
max_number_of_frames: 24

n_timesteps: 999
prompt: Amazing quality, masterpiece, A camel walking in the zoo.
negative_prompt: ""
save_ddim_reconstruction: data/davis/camel/ddim_rec # False