video_path: data/davis/bus
save_dir: data/davis/bus/ddim_latents
max_number_of_frames: 24

n_timesteps: 999
prompt: Amazing quality, masterpiece, A bus moving on the road.
negative_prompt: ""
save_ddim_reconstruction: data/davis/bus/ddim_rec # False